### ISSUE TITLE
Operators in `calc()` are incorrectly minified when using CSS nesting

### ISSUE THREAD

**Issue by kphrx** [jleeson/rollup-plugin-import-css#30]
necessary whitespace has been removed.

## nesting example

```css
div {
  height: calc(1em + 4px);

  &.hide {
    display: none;
  }
}
```

when it minify 
```css
div{height:calc(1em+4px);&.hide{display: none;}}
```

## not nesting example
```css
div {
  height: calc(1em + 4px);
}
```

when it minify
```css
div{height:calc(1em + 4px);}
```
