### ISSUE TITLE
Minification is still broken

### ISSUE THREAD

**Issue by greentore** [jleeson/rollup-plugin-import-css#31]
```css
:is(.a-very-long-class-name, .b-very-long-class-name, .c-very-long-class-name)
  textarea {
  margin: 0;
}
```

```js
import "./style.css";
```

### Result
```js
const style = ":is(.a-very-long-class-name,.b-very-long-class-name,.c-very-long-class-name)textarea{margin:0;}";
```

### The issue
Space between `:is()` and `textarea` is missing. v3.5.1 works correctly.
